### ISSUE TITLE
"Project not exists" dialog improvements / bug fix

### ISSUE THREAD

**Issue by yggdr** [python-rope/ropevim#47]
(From #36)
When creating a new rope project, the UI dialog "Project not exists in $DIR, create one?" expects the user to type "yes". Even "Yes" will abort the process. Doing so generates a notice "Project creation aborted", but also a python AttributeError. Given the formatting of the notice and the glaring red python error message, one might overlook the notice and assume an installation problem with Rope.

Please make the notice more readable, esp. by fixing the python error.
Also make the dialog accept lower- and uppercase "yes", 'y', and an empty string as positiv answer.

Thank you.

**Comment by andrewmichaelsmith** [comment]
I get this, I assume I can push "y" and get a funny error about 'NoneType' object has no attribute 'pycore'

**Comment by mcepl** [comment]
> I get this, I assume I can push "y" and get a funny error about 'NoneType' object has no attribute 'pycore'

Yes, it is confusing. You have to press "0" (that's zero) for creation of new rope project.

**Comment by andrewmichaelsmith** [comment]
Typing "yes" also seems to work fine (I've got my fix, just effectively +1ing with a bit of explanation :))

**Comment by mcepl** [comment]
If anybody has any comments on this pull request, please, speak up!
