### ISSUE TITLE
ImportError: No module named ropemode.decorators

### ISSUE THREAD

**Issue by julj** [python-rope/ropevim#48]
It seems that ropemode must be installed too, right?

```
$ vim scripts/create_dataset.py 
Error detected while processing function LoadRope:
line    4:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jul/.vim/plugged/ropevim/ropevim.py", line 6, in <module>
    import ropemode.decorators
ImportError: No module named ropemode.decorators
```

**Comment by mcepl** [comment]
Yes, see ``setup.py``.

**Comment by toomanycats** [comment]
I have the exact same issue on rhel7 with VIM 7.4
I just updated the plugin via Vundle.

Ran the setup.py install script.
I also tried to rebuild, then install.

**Comment by mcepl** [comment]
> Ran the setup.py install script.

And what was the result of the script? Did it say something on the output?

**Comment by toomanycats** [comment]
Sorry for the late reply.

I don't recall the output message, but it didn't help.
What did work, was to clone ropemode directly.

**Comment by mcepl** [comment]
Note, once again, this line in ``README``:
```
First add ropevim folder to the PYTHONPATH
(or install it using python setup.py install).
```
and take a look at https://pypi.python.org/pypi/ropevim/ … that package when properly installed pulls in ``ropemode``.
Simple
```
pip install ropevim
```
should be all needed (and yes, I should upgrade ``README``), pull request welcome.

**Comment by toomanycats** [comment]
I initially installed via conda. I know I also tried  via setup.py. The issue might be related to the order of installation.
