### ISSUE TITLE
Add ropevim package in debian

### ISSUE THREAD

**Issue by ranjanashish** [python-rope/ropevim#53]
Hi,

I saw today that `python-rope` and `python-ropemacs` packages are available from debian repositories. It would be great to see `python-ropevim` package in debian as well. Please let me know if I can help out in any way.

Thanks!

**Comment by mcepl** [comment]
I don't use Debian, so if you can help (or find somebody who could help), I am all ears.

**Comment by mcepl** [comment]
@ranjanashish that is to say, if you want to make a package, just go ahead. I don't use Debian myself, so I won't do it.

**Comment by ranjanashish** [comment]
Okay sure! I will take a shot at it (probably some time in December holidays) and let you know if I need any help otherwise. Thanks a lot for ropevim. I love it!

**Comment by mcepl** [comment]
OK, closing now, because nothing has happened so far.
