### ISSUE TITLE
disable auto code checking

### ISSUE THREAD

**Issue by n3f4s** [python-rope/ropevim#54]
Hi,
Is there a way do disable code-checking when saving a file ? I haven't found a way to do it in the ropevim documentation.

If not it would be nice to have this option.

Thanks.

**Comment by mcepl** [comment]
I don't understand what you are talking about. Rope doesn't do any code-checking I am aware off. Aren't you talking about some other vim plugin (e.g., ``vim-flake8``)?

**Comment by n3f4s** [comment]
I just checked, and yes, that's not ropevim which do code checking.
Just after I installed ropevim, there was a panel (like the one the copen vim command open) which start appearing when I save a python file. Since I haven't installed any other python plugin recently and I've found comparison between jedi (which do static anlysis) and rope, I assumed that it was rope which created those panel...
I should have checked before opening an issue. Sorry.
