### ISSUE TITLE
AutoImport imports if already imported

### ISSUE THREAD

**Issue by erikw** [python-rope/ropevim#62]
`:RopeAutoImport` should not import the given name if it is already imported. Issuing this command many times on the same symbol will just append more imports

```python
from X import Y
from X import Y
from X import Y
from X import Y
```

**Comment by mcepl** [comment]
``ropevim`` does almost nothing here. It just calls the underlying libraries, in this case I believe https://github.com/python-rope/rope/blob/master/rope/contrib/autoimport.py , so I think you should file an issue at [the rope issue tracker](https://github.com/python-rope/rope/issues).

**Comment by erikw** [comment]
Thanks. Moved to here: https://github.com/python-rope/rope/issues/194
