### ISSUE TITLE
Make ropevim python3 compatible (for Debian)

### ISSUE THREAD

**Issue by bgribble** [python-rope/ropevim#63]
For some time, Debian's vim has been built with `+python3 -python`.  See [this stackexchange question](http://vi.stackexchange.com/questions/779/how-do-i-get-vim-to-be-able-to-run-both-python-and-python3-on-a-linux-system-in) with an answer from the Debian vim maintainer.  It appears to be a packaging issue rather than an ideological or technical choice.

I spent an hour or so last night trying to make ropevim work with either python 2 or 3, and made some headway but it's not there yet.  I'll put up a PR if I get something working.  If someone else wants to do it first be my guest!

**Comment by fdjcomp** [comment]
this is the reasaon packages get a bad reputation
I had a similar frustrating experience with no real luck to get it working
much of the pyhon code seems to be for pyhon2 (and thus fails in vim debian)
a warning to this effect is the minimum requirement

**Comment by soupytwist** [comment]
I think python3 support in rope is in a much better state than it was. Can you share any specific errors? I'm curious what's lacking python3 support, not obvious from a quick look over the code.

**Comment by mcepl** [comment]
I am actually running ropevim with python3 (3.7.3) in neovim (almost 0.5.0), and it works just fine. The only problem is variable ``:ropevim_prefer_py3`` which has to be set. I will fix that momentarily.
