### ISSUE TITLE
os.path.samefile not available on Windows (Python 2.7)

### ISSUE THREAD

**Issue by forzenheart** [python-rope/ropevim#65]
when i use gvim on windows7, 
ropevim.py:  232 
os.path.samefile not available.

**Comment by mcepl** [comment]
Damn, [you are right](https://docs.python.org/2.7/library/os.path.html?highlight=samefile#os.path.samefile). ``Availability: Unix``. OK, I will try to do something about it.

**Comment by mcepl** [comment]
Could you test this pull request, please?

**Comment by forzenheart** [comment]
ok
