### ISSUE TITLE
Ropevim hangs on many operations

### ISSUE THREAD

**Issue by tngreene** [python-rope/ropevim#69]
Details:
```
Windows 10, x64,
gVim 8, Huge features, compiled Sep 6, 2017. +python/dyn, +python3/dyn
Python 3.6 being used

Vim Installation: C:\Vim
Python Installation: C:\Vim\python stuff here (I know, I got frustrated and desperate and it worked)
PYTHONPATH: C:\Vim\Lib\site-packages; Some other folders on my computer
PATH: C:\Vim; Other stuff
vim files: C:\Users\[name]\.vim\
Plugins: C:\Users\[name]\.vim\bundle

Other Python related plugins: ALE, jedi-mode, mu-complete
.ropeproject folder location:
.git
my_module
|----.ropeproject (empty)
|----example.py
```

Problem:
Using certain many commands, vim freezes up and a forced restart is required. For instance, 

1. Open example.py
2. Place cursor over MY_CONST
3. Run RopeFindOccurrences
4. On "Choose what to do: ", choose 0. search

Vim freezes

1. Open example.py
2. Run RopeRenameModule
3. Choose . for root project
4. Give new name, choose preview

Vim freezes

**Comment by tngreene** [comment]
I tried making a project using the rope python library, and now my project has a config.py file in it (the default) but FindOccurrences still fails. Perhaps I don't know how to configure this, or I don't know how to use the refactoring menus, but I would hope it would fail a little more gracefully than this.

**Comment by mcepl** [comment]
Debugging of vim Python plugins is a mess and probably not something for uninitiated. Just by looking at your information, I would be suspicious about having also installed jedi-mode and mu-complete. There has to be some clash between the plugins doing essentially the same thing. Could you try uninstall those two and try again (backup your vim configuration and try with fresh ``~/.vim`` or however it is called in the Windows world).

**Comment by mcepl** [comment]
Cannot reproduce slowness.
