### ISSUE TITLE
Problems installing Ropevim

### ISSUE THREAD

**Issue by kpace** [python-rope/ropevim#73]
Hi, I tried installing ropevim with Vundle by adding to my .vimrc `Plugin 'python-rope/ropevim'` and then running `PluginInstall`. `PluginInstall` returns that ropevim is installed successfully, but when I open a Python file and try to use a rope command, there is no sign that ropevim is installed, even though a `ropevim` directory in `~/.vim/bundle` is created.

E.g. when I press `<C-c> f` on some function/class nothing happens. When I run `:RopeFindOccurrences` I get `E492: Not an editor command: RopeFindOccurrences`.

I also tried installing it by running `python3 setup.py install` from `~/.vim/bundle/ropevim`. And when I run `pip freeze` I see packages are successfully installed but for some reason, vim is not detecting it is installed.
pip freeze output:
```
rope==0.14.0
ropemode==0.5
ropevim==0.7.0
```

I feel a bit confused about how to install it properly, thanks in advance for your help! 🙂

**Comment by mcepl** [comment]
From [README](README.rst):

> You should install rope library before using ropevim.

So, just run

```sh
$ python3 -mpip install --user
```

and be happy.

**Comment by lyh970817** [comment]
Hi, I have the same problem and have tried `$ python3 -mpip install --user rope` but doesn't seem to work. My `pip freeze` output is identical to the OP. Thanks!

**Comment by jahagirdar** [comment]
Same Problem as above. Using Vundle,
 pip3 freeze|grep rope
rope==0.17.0
ropemode==0.5
ropevim==0.8.0

I can open the helpfile but do not see the :Rope... commands.

**Comment by mcepl** [comment]
You have to do **both** installing Python modules **and** installing vim plugin.

**Comment by jahagirdar** [comment]
It is not clear what steps I have missed out, can you please clarify?
* In my .vimrc I have  'Plugin 'python-rope/ropevim'` and I have run :PluginInstall Which I believe will take care of installing the vim plugin.
* On python side, I have installed the 3 modules listed above,

Is there any other step necessary to complete the installation?

**Comment by mcepl** [comment]
Nope, it should just work. Is there any error message somewhere?

**Comment by jahagirdar** [comment]
None,
I ran vim in verbose mode "vim -V10 a.py" and saw the following

> autocommand call s:LoadFTPlugin()
> chdir(/home/vijayvithal/.vim/bundle/ropevim/ftplugin)
> fchdir() to previous dir
> line 17: sourcing "/home/vijayvithal/.vim/bundle/ropevim/ftplugin/python_ropevim.vim"
> finished sourcing /home/vijayvithal/.vim/bundle/ropevim/ftplugin/python_ropevim.vim
> continuing in <SNR>20_LoadFTPlugin

So it looks like it read in the plugin file, but i still do not see the Rope* commands...

**Comment by sinback** [comment]
I am also having this issue. `help:ropevim` works though.

**Comment by jahagirdar** [comment]
Adding the following line to my vimrc worked for me.
```
let g:ropevim_prefer_py3=1
```

**Comment by mcepl** [comment]
I see. We can make this default.

**Comment by mcepl** [comment]
> Adding the following line to my vimrc worked for me.
> 
> ```
> let g:ropevim_prefer_py3=1
> ```

If this helped you, then you have some old version of `ropevim`. At least since 0.8.0 this option should have not existed.

**Comment by jahagirdar** [comment]
I am currently at
commit 7249d6ae11c286a5a26c64c8d68be2aa7e0cd24d (HEAD -> master)
Merge: 86d9d63 0c190a3
Author: Matěj Cepl <mcepl@cepl.eu>
Date:   Thu Nov 21 15:33:26 2019 +0100

I will pull the latest changes and see whether it works without this variable....

**Comment by meicale** [comment]
> I am currently at commit [7249d6a](https://github.com/python-rope/ropevim/commit/7249d6ae11c286a5a26c64c8d68be2aa7e0cd24d) (HEAD -> master) Merge: [86d9d63](https://github.com/python-rope/ropevim/commit/86d9d63a520372463c5430e91eda1cf71af221b0) [0c190a3](https://github.com/python-rope/ropevim/commit/0c190a3b62acc2907981d81f61ad107229a1d9fc) Author: Matěj Cepl [mcepl@cepl.eu](mailto:mcepl@cepl.eu) Date: Thu Nov 21 15:33:26 2019 +0100
> 
> I will pull the latest changes and see whether it works without this variable....
> 
> Checked. With the latest version it is working without this variable.

Can you  repeat the config step of how to make this works?

**Comment by jahagirdar** [comment]
I am using Vundle as my plugin manager, so 

- `python3 -mpip install --user rope` on the commandline
- `Plugin 'python-rope/ropevim'` in the Vundle section of .vimrc followed by `:PluginInstall` in normal mode

Is sufficient.
