### ISSUE TITLE
Shorcuts created as non-recursive mapping

### ISSUE THREAD

**Issue by vecin2** [python-rope/ropevim#83]
After installing Ropevim none of the shortcuts was working even tho I could see when running the `:map`
```
...
<C-U>       * :call smooth_scroll#up(&scroll, 0, 2)<CR>
<C-C>f        :call RopeFindOccurrences()<CR>
...
```
What I've noticed on that output of that command was that shortcuts are created are a recursive mapping. 
So I wen't through all my vim config and I found that the line was breaking was following:
`noremap : <nop>`

This is the original  [issue](https://stackoverflow.com/questions/61647049/ropevim-shorcuts-not-working-it-creates-recursive-mappings/61664960#61664960) opened in stackoverflow.

**Comment by Jasha10** [comment]
I have the same issue.
